vk_token = ""
group_id = ""
server_addr = "http://127.0.0.1:1337"
api_token = ""
alarm_paper = 25
host = "127.0.0.1"
port = 1337
client_version = 0.1
salt = ""
jwt_secret = ""
admins = {'vk id администраторов'}
printers_names = {'Принтер 1': 'название принтера в бд', 'Принтер 2': 'название принтера в бд'}
printers = {'Принтер 1', 'Принтер 2'}
auth_link = ""
